#请将此文件内容添加至 Consul Key/Value 中 config/<%= PROJECT_NAME %>/data 配置路径下
spring.cloud.gateway.discovery.locator.enabled: true
management:
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"

<%_ if (tracingEnabled) { -%>
spring:
  zipkin:
    base-url: http://<%= JAEGER_HOST  || "#请输入 Jaeger 主机名" %>:<%= JAEGER_PORT || "#请输入 Jaeger 端口号" %>/
<%_ } -%>

