#请将此文件内容添加至 Consul Key/Value 中 config/<%= PROJECT_NAME %>/data 配置路径下
management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  <%_ if (messageQueueType=='RABBIT_MQ') { -%>
  #RabbitMQ 配置
  rabbitmq:
    #RabbitMQ 主机名
    host: <%= MESSAGE_QUEUE_HOST || "#请输入 RabbitMQ 主机名" %>
    #RabbitMQ 访问端口
    port: <%= MESSAGE_QUEUE_PORT || "#请输入 RabbitMQ 端口号" %>
    #RabbitMQ 虚拟主机
    virtual-host: /
    #RabbitMQ 用户名
    username: <%= MESSAGE_QUEUE_USERNAME || "#请输入 RabbitMQ 用户名" %>
    #RabbitMQ 密码
    password: <%= MESSAGE_QUEUE_PASSWORD || "#请输入 RabbitMQ 密码" %>
  <%_ } -%>
  <%_ if (messageQueueType=='KAFKA') { -%>
  kafka:
    #Kafka 地址
    bootstrap-servers: <%= MESSAGE_QUEUE_HOST && MESSAGE_QUEUE_PORT || "#请输入 Kafka 主机名:Kafka 端口号" %>
  <%_ } -%>
  <%_ if (messageQueueEnabled) { -%>
  #Spring Cloud Stream 配置
  cloud:
    stream:
      bindings:
        DEMO_QUEUE: #消息通道名称
          #消息组名称
          group: demo
          #exchange 名称，会自动创建 DEMO_QUEUE.demo 的队列
          destination: DEMO_QUEUE
          #消息数据内容类型
          content-type: application/json
  <%_ } -%>
  <%_ if (tracingEnabled) { -%>
  zipkin:
    base-url: http://<%= JAEGER_HOST  || "#请输入 Jaeger 主机名" %>:<%= JAEGER_PORT || "#请输入 Jaeger 端口号" %>/
  <%_ } -%>

