name: Publish package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Next package version. patch, minor, major or specific version.
        required: true
        default: patch

jobs:
  publish_package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update package version
        run: |
          git config --local user.email "51575374@qq.com"
          git config --local user.name "madogao"
          version="npm version --allow-same-version $VERSION"
          $version
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Publish
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        run: |
          docker build --build-arg generator_asf_version=$VERSION -t dwgao/generator-asf:$VERSION .
          docker push dwgao/generator-asf:$VERSION
        env:
          VERSION: ${{ github.event.inputs.version }}
      #- name: Push tags
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.PUSH_TOKEN }}
      #    tags: true
