name: Publish package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Next package version. patch, minor, major or specific version.
        required: true
        default: patch

jobs:
  publish_package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Update package version
        run: |
          git config --local user.email "51575374@qq.com"
          git config --local user.name "madogao"
          version="npm version $VERSION"
          $version
        env:
          VERSION: ${{github.event.inputs.version}}
      - name: Publish
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#      - name: Push changes
#        uses: alauda/generator-asf@master
#        with:
#          github_token: ${{ secrets.PUSH_TOKEN }}
#          tags: true
